name: "build_zditor"

on:
  push:
    tags:
      - "v*" # 只会在以 v 开头的标签推送时触发
jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ""
          - platform: "windows-latest"
            args: ""
    runs-on: ${{ matrix.platform }}
    steps:
      # 使用 GitHub token 访问私有仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.REPO }} # 替换为私有仓库的实际路径
          token: ${{ secrets.DEPLOY_TOKEN }} # 使用 GitHub 提供的 GITHUB_TOKEN 进行身份验证

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: npm install # change this to npm, pnpm or bun depending on which one you use.

      # 跳过 ubuntu 平台的 AppImage 构建
      - name: Skip AppImage build for Ubuntu
        if: matrix.platform == 'ubuntu-22.04'
        run: echo "Skipping AppImage build on Ubuntu."

      - name: Get latest release notes from CHANGELOG.md
        id: get_release_notes
        shell: bash
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          echo "Current tag: $TAG_NAME"

          if [ -f "CHANGELOG.md" ]; then
            echo "CHANGELOG.md exists, parsing release notes..."
            # Extract content between the current version header and next version header
            RELEASE_BODY=$(awk -v version="$TAG_NAME" '
              BEGIN { in_version = 0; first_line = 1 }
              /^## / && $2 == version { in_version = 1; next }
              /^## / && in_version { in_version = 0 }
              in_version {
                if (first_line) {
                  # Skip initial empty lines
                  if (NF) {
                    first_line = 0
                    print
                  }
                } else {
                  print
                }
              }
            ' CHANGELOG.md)
            
            echo "Raw release notes from CHANGELOG.md:"
            echo "------------------------------------"
            echo "$RELEASE_BODY"
            echo "------------------------------------"
            
            # Trim leading/trailing whitespace and empty lines (cross-platform method)
            RELEASE_BODY_TRIMMED=$(echo "$RELEASE_BODY" | sed -e ':a' -e '/./,$!d;/^\n*$/{$d;N;ba' -e '}' -e 's/[[:space:]]*$//')
            
            # Replace newlines with \n (for JSON output) - works on all platforms
            RELEASE_BODY_PROCESSED=$(echo "$RELEASE_BODY_TRIMMED" | awk '{printf "%s\\n", $0}' | sed 's/\\n$//')
            
            if [ -z "$RELEASE_BODY_PROCESSED" ]; then
              RELEASE_BODY_PROCESSED="See the assets to download this version and install."
              echo "No release notes found for this tag, using default message"
            fi
          else
            RELEASE_BODY_PROCESSED="See the assets to download this version and install."
            echo "CHANGELOG.md not found, using default message"
          fi

          echo "Final release notes that will be used:"
          echo "------------------------------------"
          echo "$RELEASE_BODY_PROCESSED"
          echo "------------------------------------"

          echo "release_body=${RELEASE_BODY_PROCESSED}" >> $GITHUB_OUTPUT
      
      
      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NODE_OPTIONS: "--max-old-space-size=4096"
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: zditor-v__VERSION__
          releaseName: "Zditor v__VERSION__"
          releaseBody: ${{ steps.get_release_notes.outputs.release_body }}
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
  sync-to-r2:
    needs: publish-tauri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract version from tag
        id: extract_version
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          VERSION="${TAG_NAME#v}" # 去掉 v 前缀
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Configure AWS CLI for R2
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
        run: |
          # Update AWS CLI (if installed)
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

          # Configure R2 access
          aws configure set aws_access_key_id "$R2_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$R2_SECRET_ACCESS_KEY"
          aws configure set default.region auto
          aws configure set default.output json

      - name: Download files from GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          # Create temporary directory
          mkdir -p release_assets
          cd release_assets

          # Define file list
          FILES=(
            "latest.json"
            "zditor-${{ steps.extract_version.outputs.version }}-1.x86_64.rpm"
            "zditor_${{ steps.extract_version.outputs.version }}_aarch64.dmg"
            "zditor_${{ steps.extract_version.outputs.version }}_amd64.AppImage"
            "zditor_${{ steps.extract_version.outputs.version }}_amd64.AppImage.sig"
            "zditor_${{ steps.extract_version.outputs.version }}_amd64.deb"
            "zditor_${{ steps.extract_version.outputs.version }}_x64-setup.exe"
            "zditor_${{ steps.extract_version.outputs.version }}_x64-setup.exe.sig"
            "zditor_${{ steps.extract_version.outputs.version }}_x64.dmg"
            "zditor_${{ steps.extract_version.outputs.version }}_x64_en-US.msi"
            "zditor_${{ steps.extract_version.outputs.version }}_x64_en-US.msi.sig"
            "zditor_aarch64.app.tar.gz"
            "zditor_aarch64.app.tar.gz.sig"
            "zditor_x64.app.tar.gz"
            "zditor_x64.app.tar.gz.sig"
          )

          # Download each file from GitHub Release
          for FILE in "${FILES[@]}"; do
            echo "Downloading $FILE..."
            curl -L -O "https://github.com/zditor/zditor-docs/releases/download/zditor-v${{ steps.extract_version.outputs.version }}/${FILE}" || echo "Failed to download $FILE"
          done

          # Verify downloaded files
          ls -lh

      - name: Process latest.json
        run: |
          cd release_assets
          
          # Update URLs in latest.json
          if [ -f "latest.json" ]; then
            echo "Processing latest.json..."
            
            # Replace GitHub URLs with R2 URLs
            jq 'walk(if type == "object" and has("url") then .url |= sub("https://github.com/zditor/zditor-docs/releases/download"; "https://download.zditor.com") else . end)' latest.json > latest_processed.json
            
            # Replace version-specific path with just the filename
            jq 'walk(if type == "object" and has("url") then .url |= sub("zditor-v[^/]+/"; "") else . end)' latest_processed.json > latest_final.json
            
            mv latest_final.json latest.json
            echo "Updated latest.json with R2 URLs:"
            cat latest.json
          else
            echo "latest.json not found, skipping processing"
          fi

      - name: Upload versioned files to R2
        env:
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
        run: |
          cd release_assets

          # Upload all files except latest.json to version directory
          for FILE in *; do
            if [ -f "$FILE" ] && [ "$FILE" != "latest.json" ]; then
              echo "Uploading $FILE to R2 version directory..."
              aws s3 cp \
                --endpoint-url "https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com" \
                "${FILE}" \
                "s3://${R2_BUCKET_NAME}/zditor-v${{ steps.extract_version.outputs.version }}/${FILE}"
            fi
          done

      - name: Upload latest.json to root of R2 bucket
        env:
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
        run: |
          cd release_assets
          
          if [ -f "latest.json" ]; then
            echo "Uploading latest.json to root of R2 bucket..."
            aws s3 cp \
              --endpoint-url "https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com" \
              "latest.json" \
              "s3://${R2_BUCKET_NAME}/latest.json"
          else
            echo "latest.json not found, skipping upload"
          fi

          echo "All files uploaded to:"
          echo "https://${R2_BUCKET_NAME}.${R2_ACCOUNT_ID}.r2.cloudflarestorage.com/"
      - name: Purge CDN Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE_ID}/purge_cache" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{"files":["https://download.zditor.com/zditor-v${{ steps.set_version.outputs.version }}/*"]}'
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}